version: "3.9"

services:
  ai_service:
    build: .
    container_name: ai_service
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./ai_service/outputs:/app/outputs
      - ./ai_service/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
